parameters:
    database_host: diabhelpxtbdd.mysql.db
    database_port: null
    database_name: diabhelpxtbdd
    database_user: diabhelpxtbdd
    database_password: N6Cqq3Dg33
    database_path: '%kernel.root_dir%/db/data.db3'
    mailer_transport: smtp
    mailer_auth_mode: login
    mailer_port: 587
    mailer_host: smtp.diabhelp.fr
    mailer_user: contact@diabhelp.fr
    mailer_password: DiabHelp31
    secret: 9d4939be09c26bf9130261566679a7d534caa334
    mailer_auth_mode: login
    mailer_port: 587

