dh_admin:
    resource: "@DHAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

dh_api:
    resource: "@DHAPIBundle/Resources/config/routing.yml"
    prefix:   /api

## DiabHelp Platform routing
dh_platform:
    resource: "@DHPlatformBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/ # Ici, on ajoute {_locale} au préfixe !
    requirements:
            _locale: en|fr

# app:
#     resource: "@AppBundle/Controller/"
#     type:     annotation

# login:
#     pattern:   /login
#     # defaults:  { _controller: DHUserBundle:Security:login }

# login_check:
#     pattern:   /login_check

# logout:
#     pattern:   /logout

## FOSUserBundle routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

login:
    path:   /{_locale}/login
    requirements:
            _locale: en|fr

rest_login:
    path:   /rest-login
    defaults:   { _controller: DHUserBundle:Security:restLogin }
    # defaults:  { _controller: DHUserBundle:Security:login }
