# app/config/security.yml
imports:
    - { resource: parameters.yml }

security:
    encoders:
        DH\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_DOCTOR:        ROLE_USER
        ROLE_PATIENT:       ROLE_USER
        ROLE_PROCHE:        ROLE_USER
        ROLE_ADMIN:         [ROLE_USER, ROLE_DOCTOR, ROLE_PATIENT, ROLE_PROCHE]
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_DOCTOR, ROLE_PATIENT, ROLE_PROCHE, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/link, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pl, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pd, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resseting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/, roles: ROLE_USER }


    providers:
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:        ^/(_(profiler|wdt)|css|images|js)/
            security:       false

        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                default_target_path: dh_platform_home
                login_path:         fos_user_security_login
                check_path:         fos_user_security_check
                success_handler:    authentication_handler
                failure_handler:    authentication_handler
            # ajax_form_login:
            #     login_path:         fos_user_security_login
            #     check_path:         fos_user_security_check
            #     success_handler:    authentication_handler
            #     failure_handler:    authentication_handler
            logout:
                path:       fos_user_security_logout
                target:     dh_platform_home
            remember_me:
                key:   "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                #always_remember_me: true
#                key:        %secret% # %secret% est un paramètre de parameters.yml
            http_basic:
                realm: "REST Service Realm"
    access_control:
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }