services:
    redirect_register_user.registration.completed:
        class: DH\UserBundle\EventListener\RegistrationConfirmListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }