dh_platform_home:
    path:     /
    defaults: { _controller: DHPlatformBundle:Diabhelp:index }

dh_platform_legal:
    path:     /legal
    defaults: { _controller: DHPlatformBundle:Diabhelp:legal }

dh_platform_theyHelpedUs:
    path:     /theyHelpedUs
    defaults: { _controller: DHPlatformBundle:Diabhelp:theyHelpedUs }

dh_platform_contact:
    path:     /contact
    defaults: { _controller: DHPlatformBundle:Diabhelp:contact }
    requirements:
        _method:  GET|POST

dh_platform_profile:
    path:     /profile
    defaults: { _controller: DHPlatformBundle:Diabhelp:profile }

dp_platform_check_available:
    path:     /check_available
    defaults: { _controller: DHPlatformBundle:Diabhelp:checkAvailable }
    requirements:
        _method:  POST

dp_platform_check_email_exist:
    path:     /check_email_exist
    defaults: { _controller: DHPlatformBundle:Diabhelp:checkEmailExist }
    requirements:
        _method:  POST

## MODULES
dh_platform_module:
    path:     /modules
    defaults: { _controller: DHPlatformBundle:Module:index }

dh_platform_module_add:
    path:     /modules/add
    defaults: { _controller: DHPlatformBundle:Module:add }

dh_platform_module_view:
    path:      /modules/{id}
    defaults:  { _controller: DHPlatformBundle:Module:view }
    requirements:
        id:  \d+

dh_platform_module_vote:
    path:      /modules/vote/{id}/{note}
    defaults:  { _controller: DHPlatformBundle:Module:vote }
    requirements:
        id:  \d+
        note: \d+

dh_platform_module_comment_delete:
    path:      /modules/deletecomment/{id}
    defaults:  { _controller: DHPlatformBundle:Module:deleteComment }
    requirements:
        id:  \d+

## ARTICLES
dh_platform_article:
    path:     /articles
    defaults: { _controller: DHPlatformBundle:Article:index }

dh_platform_article_add:
    path:     /articles/add
    defaults: { _controller: DHPlatformBundle:Article:add }

dh_platform_article_view:
    path:      /articles/{id}
    defaults:  { _controller: DHPlatformBundle:Article:view }
    requirements:
        id:  \d+

dh_platform_article_comment_delete:
    path:      /articles/deletecomment/{id}
    defaults:  { _controller: DHPlatformBundle:Article:deleteComment }
    requirements:
        id:  \d+

## CarnetSuivi

dh_platform_carnet:
    path:       /carnet
    defaults:   { _controller: DHPlatformBundle:Carnet:index}

dh_platform_carnet_exportjson:
    path:       /carnet/export
    defaults:   { _controller: DHPlatformBundle:Carnet:exportJSON}
