<?php

namespace DH\PlatformBundle\Entity;

/**
 * CommentModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
