<?php

namespace DH\PlatformBundle\Entity;

/**
 * LogbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogbookRepository extends \Doctrine\ORM\EntityRepository
{
}
