## CARNET DE SUIVI
dh_api_carnet_entry_getAllByUserId:
    path:      /carnet/entry/getAllByUserId/{id_user}
    defaults:  { _controller: DHAPIBundle:Carnet:getAllEntryByUserId }
    requirements:
        id_user:   \d+

dh_api_carnet_entry_getLastDate:
    path:      /carnet/entry/getLastDate/{id_user}
    defaults:  { _controller: DHAPIBundle:Carnet:getLastDate }
    requirements:
        id_user:   \d+

dh_api_carnet_entry_setFromApp:
    path:      /carnet/entry/setFromApp
    defaults:  { _controller: DHAPIBundle:Carnet:setFromApp }
    requirements:
        _method:  POST

dh_api_carnet_entry_delete:
    path:      /carnet/entry/delete/{id}/{id_user}
    defaults:  { _controller: DHAPIBundle:Carnet:delete }
    requirements:
        id:       \d+
        id_user:  \d+

dh_api_carnet_export:
    path:      /carnet/exportPDF
    defaults:  { _controller: DHAPIBundle:Carnet:export }

dh_api_carnet_download:
    path:      /carnet/downloadPDF/{id}
    defaults:  { _controller: DHAPIBundle:Carnet:download }
    requirements:
        id:   \d+

dh_api_carnet_exportJSON:
    path:      /carnet/exportJSON
    defaults:  { _controller: DHAPIBundle:Carnet:exportJSON }

## MODULES
dh_api_module_view:
    path:      /modules/{id}
    defaults:  { _controller: DHAPIBundle:Module:view }
    requirements:
        id:  \d+

dh_api_module_all:
    path:      /modules/all
    defaults:  { _controller: DHAPIBundle:Module:all }

## USERS
dh_api_user_register:
    path:      /user/register
    defaults:  { _controller: DHAPIBundle:User:register }

dh_api_user_logout:
    path:      /user/logout/{token}
    defaults:  { _controller: DHAPIBundle:User:logout }
    requirements:
        token:  \d+
