<?php

namespace DH\PlatformBundle\Entity;

/**
 * CommentArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
